apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kubernetes-cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cron-batch-job-call-api
        spec:
          restartPolicy: OnFailure
          containers:
            - name: kube-cron-job-call-api
              imagePullPolicy: IfNotPresent
                command:
                  - curl
                  - "http://my.first.k8s.com/cronJob"